#--- From tmux sensible (https://github.com/tmux-plugins/tmux-sensible)
# Set 256 color terminal
set -g default-terminal "screen-256color"

# utf8 is on
set -g utf8 on
set -g status-utf8 on

# address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# increase scrollback buffer size
set -g history-limit 50000

# tmux messages are displayed for 4 seconds
set -g display-time 4000

# refresh 'status-left' and 'status-right' more often
set -g status-interval 5

# set only on OS X where it's required
set -g default-command "reattach-to-user-namespace -l $SHELL"

# upgrade $TERM
set -g default-terminal "screen-256color"

# emacs key bindings in tmux command prompt (prefix + :) are better than
# vi keys, even for vim users
set -g status-keys emacs

# focus events enabled for terminals that support them
set -g focus-events on

# super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

# easier and faster switching between next/prev window
bind C-p previous-window
bind C-n next-window

# source .tmux.conf as suggested in `man tmux`
bind R source-file ~/.tmux.conf

#--- My config starts here

# Change prefix to Ctrl-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# easier and faster switching between panes
bind h select-pane -L
bind j select-pane -U
bind k select-pane -R
bind l select-pane -R

# Display
# Centered Window List
set -g status-justify centre

#--- Deprecated stuff
# set -g status-keys vi
# setw -g mode-keys vi
